// public/react-app/src/components/paging.component.tsx
import React, { useEffect, useState } from 'react';


type Props = {
  totalDocs: number,
  onPageChange:Function,
}

export default function({ totalDocs,onPageChange }:Props) {
  let [currentPage,setCurrentPage] = useState<number>(0);
  let [totalPages,setTotalPages] = useState<number>(0);
  let [docs,setDocs] = useState<number>(0);

  useEffect(() => {
    // console.log('effect');
   
    let total = Math.ceil(totalDocs / parseInt(process.env.REACT_APP_ROWS_PER_PAGE || '',10));
    // console.log('docs',docs);
    // console.log('totaldocs',totalDocs);
    if(docs != totalDocs){
      // setTimeout(() => {
        setCurrentPage(0);
        setDocs(totalDocs);
        setTotalPages(total);
        
      // },10)
    }
  });

  const onPrevious = () => {
    if(currentPage > 0){
      currentPage = currentPage -1;
      setCurrentPage(currentPage);
      onPageChange(currentPage);
    }
  }

  const onNext = () => {
    console.log('onnext');
    if(currentPage < totalPages){
      currentPage = currentPage + 1;
      setCurrentPage(currentPage);
      onPageChange(currentPage);
    }
  }

  return (
    <nav>
      <ul className="pagination">
        <li className="page-item">
          <button className="page-link" disabled={currentPage <= 0} onClick={() => onPrevious()}>Previous</button>
        </li>
        <li className="page-item">
          <button className="page-link" disabled={currentPage == totalPages-1} onClick={() => onNext() }>Next</button>
        </li>
      </ul>
    </nav>
  );
}

// public/angular-app/src/app/components/paging/paging.component.ts
import {
  Component,
  Input,
  OnInit,
  Output,
  EventEmitter,
  OnChanges,
  SimpleChanges,
} from '@angular/core';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'app-paging',
  templateUrl: './paging.component.html',
  styleUrls: ['./paging.component.css'],
})
export class PagingComponent implements OnInit, OnChanges {
  @Input() totalDocs: number = 0;
  @Output() pageClickEvent = new EventEmitter<number>();

  totalPages: number = 0;
  pageNo: number = 0;
  currentPage: number = 0;
  constructor() {}

  ngOnChanges(changes: SimpleChanges): void {
    this.currentPage=0;
    this.totalPages = Math.ceil(this.totalDocs / environment.limitRowCount);
  }

  ngOnInit(): void {}

  emitEvent(): void {
    this.pageClickEvent.emit(this.currentPage);
  }

  onPrevious() {
    if (this.currentPage > 0) {
      this.currentPage--;
      this.emitEvent();
    }
  }

  onNext() {
    if (this.currentPage < this.totalPages) {
      this.currentPage++;
      this.emitEvent();
    }
  }
}

<nav>
  <ul class="pagination">
    <li class="page-item"><button class="page-link" (click)="onPrevious()" [disabled]="currentPage <= 0">Previous</button></li>
    <li class="page-item"><button class="page-link" (click)="onNext()" [disabled]="currentPage == totalPages-1" >Next</button></li>
  </ul>
</nav>
