// public/react-app/src/components/login-form.component.tsx
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useNavigate } from 'react-router-dom';
import authenticationService from '../services/authentication.service';

export default function() {
  const navigate = useNavigate();
  const [errMsg,setErrMsg] = useState<string>('');
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();

  const onSubmit = (credentials: any) => {
    authenticationService.getInstance().login(credentials)
    .then((response:any) =>{
      authenticationService.getInstance().setToken(response.data.token);
      navigate('/travelings');
    })
    .catch((err:any) => {
      // console.log(err)
      setErrMsg(err.response.data);
    })
  };
  return (
    <form className="form-signin" onSubmit={handleSubmit(onSubmit)}>
      <h1 className="h6 mb-3 font-weight-normal">Please sign in</h1>

      <label className="sr-only">User name</label>
      <input type="text" className="form-control" placeholder="username" {...register('username',{required:true})}/>

      <label className="sr-only">Password</label>
      <input type="password" className="form-control" placeholder='password' {...register('password',{required:true})} />
      {
        errMsg != '' && <div className="alert alert-danger">{errMsg}</div>
      }
      <div className="form-group">
        <button className="btn btn-primary btn-block" type="submit">
          Sign in
        </button>
      </div>

      <div className="mb-3">
        <label>Not a memeber?</label>
        <span>&nbsp;</span>
        <Link to="/register">Register</Link>
      </div>

    </form>
  );
}

// public/angular-app/src/app/components/login-form/login-form.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { NgForm } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthenticationService } from 'src/app/services/authentication.service';
import { UsersDataService } from 'src/app/services/users-data.service';

@Component({
  selector: 'app-login-form',
  templateUrl: './login-form.component.html',
  styleUrls: ['./login-form.component.css']
})
export class LoginFormComponent implements OnInit {
  @ViewChild('loginForm')
  loginForm!:NgForm;
  errorMsg:string='';

  constructor(private router:Router,
    private authService:AuthenticationService) { }

  ngOnInit(): void {
    setTimeout(()=>{
      this.loginForm.setValue({
        username:'',
        password:''
      })
    });
  }

  onSubmit():void{
    this.authService.login(this.loginForm.value).then(response =>{
      this.authService.setToken(response.token);
      this.router.navigate(['/travelings']);
    }).catch(err => this.errorMsg = err);
  }

}

<form class="form-signin" #loginForm="ngForm" (ngSubmit)="onSubmit()">
  <div class="form-row">

    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">@</span>
      </div>
      <input
        type="text"
        id="username"
        name="username"
        class="form-control"
        required="true"
        autofocus="true"
        ngModel
        placeholder="Username"
      />
    </div>

    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text"><i class="fa-solid fa-lock"></i></span>
      </div>
      <input
        type="password"
        id="password"
        name="password"
        class="form-control"
        placeholder="password"
        required="true"
        ngModel
      />
    </div>

    <button
      class="btn btn-primary btn-block"
      type="submit"
      [disabled]="!loginForm.valid"
    >
      Login
    </button>
  </div>
  <div class="error-text" *ngIf="errorMsg != ''">
    {{ errorMsg }}
  </div>
</form>

<!-- <form class="form-signin" #loginForm="ngForm" (ngSubmit)="onSubmit()">
  <h1 class="h6 mb-3 font-weight-normal">Please sign in</h1>
  <label for="username" class="sr-only">User name</label>
  <input
    type="text"
    id="username"
    name="username"
    class="form-control"
    placeholder="username"
    required="true"
    autofocus="true"
    ngModel
  />

  <label for="password" class="sr-only">Password</label>
  <input
    type="password"
    id="password"
    name="password"
    class="form-control"
    placeholder="password"
    required="true"
    ngModel
  />
  <div class="alert alert-danger" *ngIf="errorMsg != ''">
    {{ errorMsg }}
  </div>
  <div class="form-group">
    <button
      class="btn btn-primary btn-block"
      type="submit"
      [disabled]="!loginForm.valid"
    >
      Sign in
    </button>
  </div>

  <div class="mb-3">
    <label>Not a memeber?</label>
    <span>&nbsp;</span>
    <a routerLink="/register">Register</a>
  </div>
</form> -->
