// public/angular-app/src/app/components/traveling-form/traveling-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { ActivatedRoute,Router } from '@angular/router';
import { AuthenticationService } from 'src/app/services/authentication.service';
import { Traveling } from '../../models/traveling.model';
import { TravelingDataService } from '../../services/traveling-data.service';

@Component({
  selector: 'app-traveling-form',
  templateUrl: './traveling-form.component.html',
  styleUrls: ['./traveling-form.component.css']
})
export class TravelingFormComponent implements OnInit {
  title:string='';
  travelingForm!: FormGroup;
  travelingId!:string;

  constructor(private travelingService:TravelingDataService,
    private activatedRoute:ActivatedRoute,
    private router:Router,
    public authService:AuthenticationService) { }

  ngOnInit(): void {
    this.travelingId = this.activatedRoute.snapshot.params['travelingId'];

    this.travelingForm = new FormGroup({
      destination: new FormControl(''),
      stayAt: new FormControl(''),
      length: new FormControl(0)
    })

    if(this.travelingId){
      this.getOne();
    }
  }

  onSubmit(){
    if(this.travelingId){
      this.travelingService.updateOne(this.travelingId, this.travelingForm.value).subscribe(traveling => this.router.navigate(['/travelings']));
    }else{
      this.travelingService.createOne(this.travelingForm.value).subscribe(traveling => this.router.navigate(['/travelings']));
    }
  }

  getOne(){
    this.travelingService.getOne(this.travelingId).subscribe(traveling => this.populateDataToControl(traveling));
  }

  populateDataToControl(traveling:Traveling){
    this.travelingForm = new FormGroup({
      destination: new FormControl(traveling.destination),
      stayAt: new FormControl(traveling.stayAt),
      length: new FormControl(traveling.length)
    })
  }

  onTransportClick(){
    this.router.navigate([`/travelings/${this.travelingId}/transportations`]);
  }

}


<div class="form-content">
  <form [formGroup]="travelingForm" (ngSubmit)="onSubmit()">

    <label for="destination">Destination</label>
    <input type="text" id="destination" formControlName="destination" class="form-control" required="true"/>

    <label>Stay at</label>
    <input type="text" formControlName="stayAt" class="form-control"  required="true" />

    <label>Length</label>
    <input type="text" formControlName="length"  class="form-control" required="true"/>
    <div *ngIf="travelingForm.value.length < 0" class="alert alert-danger">
      Length should be greater than 0
    </div>

    <button class="btn btn-secondary" (click)="onTransportClick()" [disabled]="!travelingId">Transportions</button>


    <div *ngIf="this.authService.isLoggedIn" class="form-group">
      <button
        class="btn btn-primary"
        type="submit"
        [disabled]="!travelingForm.valid"
      >
        Save
      </button>
      
    </div>
  </form>
  
</div>

// public/react-app/src/components/traveling-form.component.tsx
import React, { useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import Traveling from '../models/travelings.model';
import travelingService from '../services/traveling.service';
import Authentication from '../services/authentication.service';

export default function TravelingForm() {
  const navigate = useNavigate();
  const params = useParams();
  const { register, handleSubmit, setValue, formState:{ errors }} = useForm<Traveling>();

  useEffect(() => {
    let travelingId = params.travelingId;
    if(travelingId){
      travelingService.getOne(travelingId)
      .then((response) => {
        const traveling:Traveling = response.data;
        setValue('destination',traveling.destination);
        setValue('length',traveling.length);
        setValue('stayAt',traveling.stayAt);
      });
    }
  });

  const onSubmit = (traveling:any) =>{
    let id = params.id;
    
    if(id && id != ''){
      //update
      travelingService.updateOne(id,traveling)
      .then((response) => {
        navigate('/travelings');
      })
      .catch((err) => console.log(err));
    }else{
      //create
      travelingService.createOne(traveling)
      .then((response) => {
        navigate('/travelings');
      })
      .catch((err) => console.log(err));
    }
  }
//travelings/:travelingId/transportations
  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <label>Destination</label>
      <input type="text" id="destination" {...register('destination',{required:true})} 
      className="form-control"  />
      {errors.destination && <span>Destination is required</span>}

      <label>Stay at</label>
      <input type="text" {...register('stayAt')} className="form-control"  />

      <label>Length</label>
      <input type="text" {...register('length')} className="form-control"  />

      <button className="btn btn-secondary" onClick={() => navigate('/travelings/'+params.travelingId+'/transportations')}>Transportions</button>

      <div className="form-group">
        {
          Authentication.getInstance().token !== null &&
          <button className="btn btn-primary" type="submit" >
          Save
        </button>
        }

      </div>
    </form>
  );
}
