// public/react-app/src/components/register.component.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import Credentials from '../models/credentials.model';
import authenticationService from '../services/authentication.service';

export default function() {
  const naviage = useNavigate();
  const { register, handleSubmit, watch, formState:{errors}} = useForm();

  const onSubmit = (credentials:any) => {
    authenticationService.getInstance()
    .register(credentials)
    .then((response) => naviage('/login'))
    .catch(err => console.log(err));

  }
  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <h1 className="h6 mb-3 font-weight-normal">Please register</h1>
      <label>Name</label>
      <input
        type="text"
        className="form-control"
        placeholder="name"
        required
        {...register('name',{required:true})}
      />

      <label>User name</label>
      <input
        type="text"
        className="form-control"
        placeholder="user name"
        required
        {...register('username',{required:true})}
      />

      <label>Password</label>
      <input
        type="password"
        className="form-control"
        placeholder="password"
        required
        {...register('password',{required:true})}
      />

      <label>Confirm Password</label>
      <input
        type="password"
        className="form-control"
        placeholder="Confirm password"
        required
        {...register('confirmPassword',{required:true})}
      />

      <button className="btn btn-primary btn-block" type="submit">
        Register
      </button>
    </form>
  );
}

// public/angular-app/src/app/components/register/register.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { NgForm } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthenticationService } from 'src/app/services/authentication.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {
  @ViewChild('registerForm')
  registerForm!:NgForm;
  errorMsg:string='';

  constructor(public authService:AuthenticationService,private router:Router) { }

  ngOnInit(): void {
    setTimeout(()=>{
      this.registerForm.setValue({
        name:'',
        username:'',
        password:'',
        repeatPassword:'',
      });
    });
  }

  onSubmit():void{
    if(this.registerForm.valid){
      this.authService.register(this.registerForm.value)
      .then(response => this.router.navigate(['/']))
      .catch(err => this.errorMsg = err);
    }
  }


}

<form *ngIf="!this.authService.isLoggedIn" class="form-register" #registerForm="ngForm" (ngSubmit)="onSubmit()">
  <h1 class="h6 mb-3 font-weight-normal">Please register</h1>
  <label for="name">Name</label>
  <input
    type="text"
    id="name"
    name="name"
    class="form-control"
    placeholder="name"
    required
    autofocus="true"
    ngModel
  />

  <label for="username">User name</label>
  <input
    type="text"
    id="username"
    name="username"
    class="form-control"
    placeholder="user name"
    required
    ngModel
  />

  <label for="password">Password</label>
  <input
    type="password"
    id="password"
    name="password"
    class="form-control"
    placeholder="password"
    required
    ngModel
    #password="ngModel"
  />


  <label for="repeatPassword">Confirm Password</label>
  <input
    type="password"
    id="repeatPassword"
    name="repeatPassword"
    class="form-control"
    placeholder="Confirm password"
    required
    ngModel
    #repeatPassword="ngModel"
  />

  <div
    *ngIf="repeatPassword.valid && (repeatPassword.dirty || repeatPassword.touched)"  >
    <div
      *ngIf="registerForm.value.password != registerForm.value.repeatPassword"
      class="alert alert-danger"
    >
      Password and confirm password should be the same.
    </div>
  </div>

  <button
    class="btn btn-primary btn-block"
    type="submit"
    [disabled]="!registerForm.valid"
  >
    Register
  </button>

  <div *ngIf="this.errorMsg != ''" class="alert alert-danger" >
    {{this.errorMsg}}
  </div>
</form>
