// public/react-app/src/components/travelings.component.tsx
import React, { ChangeEvent, useEffect, useState } from 'react';
import { Link,useNavigate } from 'react-router-dom';
import Traveling from '../models/travelings.model';
import Authentication from '../services/authentication.service';
import travelingService from '../services/traveling.service';
import PagingComponent from './paging.component';

export default function Travelings() {
  let [travelings, setTravelings] = useState<Traveling[]>([]);
  // const [pageNo, setPageNo] = useState<number>(0);
  let [destination,setDestination] = useState<string>('');
  let [totalDocs,setTotalDocs] = useState<number>(0);
  const navigate = useNavigate();

  useEffect(() => {
    // console.log('effect');
    
    getTotalDocs(0);
  },[]);

  const getTotalDocs = (no:number) => {
    travelingService.getTotalDocs(destination)
    .then((response:any) => calculatePagingAndPopulateData(response.data,no))
    .catch((err) => console.log(err));
  }

  const calculatePagingAndPopulateData = (docs: number,no:number) => {
    setTotalDocs(docs);
    // console.log('docs',docs);
    
    let offset = no * parseInt(process.env.REACT_APP_ROWS_PER_PAGE || '',10);
    getAll(offset,parseInt(process.env.REACT_APP_ROWS_PER_PAGE || ''), destination);
  }

  const getAll = (offset:number,count:number,destination:string) => {
    travelingService
      .getAll(offset,count,destination)
      .then((response) =>  setTravelings(response.data))
      .catch((err) => {
        console.log(err);
      });
  }

  const onAddNew = () => {
    navigate('/travelings/add');
  }

  const onEdit = (id:string) =>{
    navigate('/travelings/' + id);
  }

  const reload = (no:number) => {
    // await setPageNo(no);
    getTotalDocs(no);
  }

  const onDelete = (id:string) => {
    if (confirm('Are you sure you want to delete?') === true) {
      travelingService
        .deleteOne(id)
        .then((response) => {
          // setIsReload(true);
          reload(0);
        })
        .catch(err => console.log(err));
    }
  }

  const onView = (id:string)=>{
    navigate('/travelings/' + id);
  }

  const onSearch = () => {
    reload(0);
  }

  const handleDestinationChange = (e:React.FormEvent<HTMLInputElement>) =>{
    setDestination(e.currentTarget.value);
  }

  return (
    <>
    
    <div className="input-group col-md-4">
      <input
        type="text"
        className="form-control mb-3"
        placeholder="destination" onChange={(e) => handleDestinationChange(e)} />

      <span>&nbsp;</span>
      <div className="input-group-append">
        <button className="btn btn-outline-secondary" onClick={() => onSearch()} type="button">
          Search
        </button>
        <span>&nbsp;</span>
        {
          Authentication.getInstance().token &&
          <button className="btn btn-outline-secondary" type="button" onClick={() => onAddNew()}>
          Add new
          </button>
        }

      </div>
    </div>
    
    <table className="table">
        <thead>
          <tr>
            <th>Destination</th>
            <th>Stay At</th>
            <th>Length (Days)</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {travelings.map((item, index) => (
            <tr key={index}>
              <td>{item.destination}</td>
              <td>{item.stayAt}</td>
              <td>{item.length}</td>
              <td>
                { Authentication.getInstance().token == null &&
                  <a onClick={()=> onView(item._id)} className="fa-solid fa-eye"></a>
                }
                { Authentication.getInstance().token !== null &&
                <a
                onClick={()=> onEdit(item._id)}
                className="fa-solid fa-pen-to-square"
              ></a>
                }

              </td>
              <td>
                { Authentication.getInstance().token !== null &&
                  <a className="fa-solid fa-circle-minus" onClick={()=> onDelete(item._id)}></a>
                }
                
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      
      <div>
        <PagingComponent totalDocs={totalDocs} onPageChange={reload}/>
      </div>

      </>

  );
}

// public/angular-app/src/app/components/travelings/travelings.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthenticationService } from 'src/app/services/authentication.service';
import { environment } from 'src/environments/environment';
import { Traveling } from '../../models/traveling.model';
import { TravelingDataService } from '../../services/traveling-data.service';

@Component({
  selector: 'app-travelings',
  templateUrl: './travelings.component.html',
  styleUrls: ['./travelings.component.css'],
})
export class TravelingsComponent implements OnInit {
  travelings: Traveling[] = [];
  totalDocs: number = 0;
  pageNo: number = 0;
  destination: string = '';

  constructor(private travelingService: TravelingDataService,
    public authService:AuthenticationService) {}

  ngOnInit(): void {
    this.getTotalDocs();
  }

  getAll(offset: number, count: number, destination: string) {
    this.travelingService
      .getAll(offset, count, destination)
      .subscribe((traveling) => (this.travelings = traveling));
  }

  deleteOne(travelingId: string) {
    if (confirm('Are you sure you want to delete?') === true) {
      this.travelingService
        .deleteOne(travelingId)
        .subscribe((traveling) => this.reload(0));
    }
  }

  getTotalDocs() {
    this.travelingService
      .getTotalDocs(this.destination)
      .subscribe((totalDocs) => this.calculatePagingAndPopulateData(totalDocs));
  }

  calculatePagingAndPopulateData(totalDocs: number) {
    this.totalDocs = totalDocs;
    let offset = this.pageNo * environment.limitRowCount;
    this.getAll(offset, environment.limitRowCount, this.destination);
  }

  reload(pageNo: number) {
    this.pageNo = pageNo;
    this.getTotalDocs();
  }

  onSearch() {
    this.pageNo = 0;
    this.getTotalDocs()
  }
}

<div>
  
  <div class="form-content "> 
    <div class="input-group col-md-4">
      <input
        type="text"
        class="form-control mb-3"
        [(ngModel)]="destination"
        placeholder="destination"
      />
      <span>&nbsp;</span>
      <div class="input-group-append">
        <button
          class="btn btn-outline-secondary"
          (click)="onSearch()"
          type="button"
        >
          Search
        </button>
        <span>&nbsp;</span>
        <button
          [hidden]="!this.authService.isLoggedIn"
          class="btn btn-outline-secondary"
          routerLink="/travelings/add"
          type="button"
        >
          Add new
        </button>
      </div>
    </div>

    <div>&nbsp;</div>
    <!--Table-->
    <table class="table">
      <thead class="thead-light">
        <th scope="col">Destination</th>
        <th scope="col">Stay At</th>
        <th scope="col">Length (Days)</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </thead>
      <tbody>
        <tr *ngFor="let t of travelings">
          <td>{{ t.destination }}</td>
          <td>{{ t.stayAt }}</td>
          <td>{{ t.length | number: "1.0-1" }}</td>
          <td>
            <a
              [hidden]="!this.authService.isLoggedIn"
              class="fa-solid fa-pen-to-square"
              routerLink="/travelings/{{ t._id }}"
              alt="edit"
            ></a>
            <a 
            [hidden]="this.authService.isLoggedIn"
            class="fa-solid fa-eye"
            routerLink="/travelings/{{ t._id }}"
            alt="view"
            ></a>
          </td>
          <td>
            <a
              [hidden]="!this.authService.isLoggedIn"
              class="fa-solid fa-circle-minus"
              alt="delete"
              (click)="deleteOne(t._id)"
            ></a>
          </td>
        </tr>
      </tbody>
    </table>
    <!--Paging-->
    <app-paging
      [totalDocs]="totalDocs"
      (pageClickEvent)="reload($event)"
    ></app-paging>
  </div>
</div>
