// public/react-app/src/components/login-bar.component.tsx
import React, { useEffect, useState, useSyncExternalStore } from 'react';
import { useNavigate } from 'react-router-dom';
import Authentication from '../services/authentication.service';

export default function() {
  const navigate = useNavigate();

  useEffect(() => {

  });

  console.log(Authentication.getInstance().token);
  

  const onLogin = () => {
    navigate('/login');
  };

  const onLogout = () => {
    Authentication.getInstance().logout();
    navigate('/');
  }

  return (
    <div className="login">
      <label>Hi {Authentication.getInstance().username} !</label>
      {(Authentication.getInstance().token != null) && (
        <a className="btn btn-primary ms-2 me-1" onClick={() => onLogout()}>Logout</a>
      )}
      { Authentication.getInstance().token == null  && (
        <a className="btn btn-primary ms-2 me-1" onClick={() => onLogin()}>
          Login
        </a>
      )}
    </div>
  );
}

// public/angular-app/src/app/components/login-bar/login-bar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthenticationService } from 'src/app/services/authentication.service';

@Component({
  selector: 'app-login-bar',
  templateUrl: './login-bar.component.html',
  styleUrls: ['./login-bar.component.css']
})
export class LoginBarComponent implements OnInit {

  constructor(private router: Router, public authService:AuthenticationService) { }

  ngOnInit(): void {
  }

  onLogin(){
    this.router.navigate(['/login']);
  }

  onLogout(){
    this.authService.logout();
    this.router.navigate(['/']);

  }
}

<div class="login">
  <app-login-form *ngIf="!this.authService.isLoggedIn"></app-login-form>
  <label [hidden]="!this.authService.isLoggedIn">Hi {{this.authService.name}}!</label>
  <a *ngIf="this.authService.isLoggedIn" class="btn btn-primary ms-2 me-1" (click)="onLogout()">Logout</a>
  <!-- <a  *ngIf="!this.authService.isLoggedIn" class="btn btn-primary ms-2 me-1" (click)="onLogin()">Login</a> -->
  
</div>
